notebooks:

	tools/nb_to_doc.py aesthetics
	tools/nb_to_doc.py color_palettes 
	tools/nb_to_doc.py distributions
	tools/nb_to_doc.py quantitative_linear_models
	tools/nb_to_doc.py categorical_linear_models
	tools/nb_to_doc.py dataset_exploration
	tools/nb_to_doc.py axis_grids
