tutorials := basic.rst categorical.rst distributions.rst regression.rst axis_grids.rst aesthetics.rst color_palettes.rst

notebooks: ${tutorials}

basic.rst: basic.ipynb
	../tools/nb_to_doc.py basic 

categorical.rst: categorical.ipynb
	../tools/nb_to_doc.py categorical

distributions.rst: distributions.ipynb
	../tools/nb_to_doc.py distributions

regression.rst: regression.ipynb
	../tools/nb_to_doc.py regression

axis_grids.rst: axis_grids.ipynb
	../tools/nb_to_doc.py axis_grids

aesthetics.rst: aesthetics.ipynb
	../tools/nb_to_doc.py aesthetics

color_palettes.rst: color_palettes.ipynb
	../tools/nb_to_doc.py color_palettes 
